socket: 'tcp://127.0.0.1:8282'
timeout: 500
actions:
    leftClick:
        type: 'mouse'
        action: 'hold'
        tearDown: 'mouse1Up'
        target: 'left'
    rightClick:
        type: 'mouse'
        action: 'hold'
        tearDown: 'mouse2Up'
        target: 'right'
    mouse1Up:
        type: 'mouse'
        action: 'release'
        target: 'left'
    mouse2Up:
        type: 'mouse'
        action: 'release'
        target: 'right'
    mouse1Down:
        type: 'mouse'
        action: 'down'
        target: 'left'
    mouse2Down:
        type: 'mouse'
        action: 'down'
        target: 'right'
    mouseMove:
        type: 'mouse'
        action: 'move'
    holdMouse:
        type: 'mouse'
        action: 'hold'
signs:
    pinchIndex:
        pinch:
            pincher: 'indexFinger'
            min: 0.5
    pinchRing:
        pinch:
            pincher: 'ringFinger'
            min: 0.5
    unpinch:
        pinch:
            max: 0.5
    freeHand:
        grab:
            max: 0.5
recipes:
    holdMouse1:
        sign: 'pinchIndex'
        action: 'mouse1Down'
    holdMouse2:
        sign: 'pinchRing'
        action: 'mouse2Down'
    mouseMove:
        action: 'mouseMove'
        sign: 'freeHand'